---
name: CI
"on":
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: ">=1.24"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5
          args: "--timeout=30m"
      - run: make lint
